basic_settings:
    site_title: Dẫn Truyện
    favicon_image: /images/favicon.png

menu_settings:
    menu_items:
        - title: 'Browse'
          url: '/browse/'
        - title: 'User Profile'
          url: '/user-profile/'
        - title: 'Game'
          url: '/game/'
        - title: 'Nạp Tem'
          url: '/tem/'
